[build]
  base = "client"
  command = "npm run build"
  publish = "build"

# Client size
[context.client]
  [context.client.build]
    base = ""
    command = "npm run build"
    publish = "dist"

# Admin site
[context.admin]
  [context.admin.build]
    base = "admin"
    command = "npm run build"
    publish = "dist"
