# Client size
[context.client]
  [context.client.build]
    base = "client"
    command = "npm run build"
    publish = "dist"

# Admin site
[context.admin]
  [context.admin.build]
    base = "admin"
    command = "npm run build"
    publish = "dist"
